// <auto-generated />
namespace Shopping_portal1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class first_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first_name));
        
        string IMigrationMetadata.Id
        {
            get { return "202110160817587_first_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
