//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myproj
{
    using System;
    using System.Collections.Generic;
    
    public partial class cust
    {
        public int userid { get; set; }
        public string usrname { get; set; }
        public string pwd { get; set; }
        public string address1 { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
    }
}
