//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapiproj
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public int empno { get; set; }
        public string empname { get; set; }
        public string job { get; set; }
        public Nullable<int> deptno { get; set; }
        public Nullable<int> salary { get; set; }
    }
}
